In [ ]:
#4.1
#PROBLEM-1: ARRAY CREATION

import numpy as np

empty_array = np.empty((2,2))
print(empty_array)

ones_array = np.ones((4,2))
print(ones_array)

filled_array = np.full((3,3), 7)
print(filled_array)

zeros_like_array = np.zeros_like(filled_array)
print(zeros_like_array)

ones_like_array = np.ones_like(filled_array)
print(ones_like_array)

new_list = [1,2,3,4]
array_from_list = np.array(new_list)
print(array_from_list)


[[5.10033891e-315 0.00000000e+000]
 [6.79290527e-310 5.77904633e-317]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1 2 3 4]


In [ ]:
#PROBLEM-2: ARRAY MANIPULATION
import numpy as np

arr_10_49 = np.arange(10,50)
print(arr_10_49)

matrix_0_8 = np.arange(9).reshape((3,3))
print(matrix_0_8)

identity_matrix = np.eye(3)
print(identity_matrix)

rand_array_30 = np.random.random(30)
print(rand_array_30)
print(rand_array_30.mean())

rand_10x10 = np.random.random((10,10))
print(rand_10x10)
print(rand_10x10.min(), rand_10x10.max())

zero_10 = np.zeros(10)
zero_10[4] = 1
print(zero_10)

arr_to_reverse = np.array([1,2,0,0,4,0])
reversed_arr = arr_to_reverse[::-1]
print(reversed_arr)

border_array = np.ones((5,5))
border_array[1:-1,1:-1] = 0
print(border_array)

checkerboard = np.zeros((8,8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.36664358 0.81044281 0.75827895 0.20842324 0.63079873 0.20781228
 0.73155246 0.95524877 0.1199571  0.11316463 0.18129002 0.40721365
 0.05198999 0.49398488 0.15026993 0.48780292 0.64983043 0.63886546
 0.04299473 0.43853981 0.92973319 0.93047915 0.97647472 0.45700833
 0.24551219 0.8066331  0.61885075 0.23379729 0.19015933 0.50688001]
0.4780210811314745
[[0.80422323 0.75821383 0.29374306 0.51664754 0.55804342 0.17331076
  0.11293998 0.18052982 0.70551063 0.79012252]
 [0.15075042 0.64817407 0.70279995 0.20104324 0.71896339 0.09702649
  0.52529033 0.13201455 0.1538468  0.05917548]
 [0.52635528 0.91604061 0.83108746 0.33662157 0.45442766 0.70240484
  0.51631641 0.85216834 0.32650122 0.39266348]
 [0.74829291 0.58676026 0.44007457 0.66269126 0.64969822 0.67674739
  0.50083419 0.05190865 0.92541857 0.7267327

In [ ]:
#PROBLEM-3: ARRAY OPERATION
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print(x + y)
print(x - y)
print(x * 2)
print(x**2)
print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))
print(np.concatenate((x,y), axis=0))
print(np.vstack((v,w)))
print("Cannot concatenate x and v directly because shapes are different.")


[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 2  4]
 [ 6 10]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]
Cannot concatenate x and v directly because shapes are different.


In [ ]:
#PROBLEM-4: MATRIX OPERATION
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

A_inv = np.linalg.inv(A)
print(np.dot(A, A_inv))

AB = np.dot(A,B)
BA = np.dot(B,A)
print(AB)
print(BA)

AB_T = (AB).T
B_TA_T = np.dot(B.T, A.T)
print(AB_T)
print(B_TA_T)

coeff = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
const = np.array([-1,-3,9])
solution = np.dot(np.linalg.inv(coeff), const)
print(solution)


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
[[23 51]
 [13 29]]
[[23 51]
 [13 29]]
[ 2.  1. -2.]


In [ ]:
#4.2
#1. Element-wise Addition:
import numpy as np
import time

size = 1000000
list1 = list(range(size))
list2 = list(range(size))

# Python list addition
start = time.time()
add_list = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print("Python list addition time:", end-start)

# Numpy array addition
arr1 = np.array(list1)
arr2 = np.array(list2)
start = time.time()
add_np = arr1 + arr2
end = time.time()
print("Numpy array addition time:", end-start)


Python list addition time: 0.1090857982635498
Numpy array addition time: 0.0056056976318359375


In [ ]:
#3. Element-wise Multiplication:
import numpy as np
import time

size = 1000000
list1 = list(range(size))
list2 = list(range(size))


start = time.time()
mult_list = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("Python list multiplication time:", end-start)

arr1 = np.array(list1)
arr2 = np.array(list2)
start = time.time()
mult_np = arr1 * arr2
end = time.time()
print("Numpy array multiplication time:", end-start)


Python list multiplication time: 0.4362771511077881
Numpy array multiplication time: 0.0051267147064208984


In [ ]:
#3. Dot Product
import numpy as np
import time

size = 1000000
list1 = list(range(size))
list2 = list(range(size))

# Python list dot product
start = time.time()
dot_list = sum([list1[i] * list2[i] for i in range(size)])
end = time.time()
print("Python list dot product time:", end-start)

# Numpy array dot product
arr1 = np.array(list1)
arr2 = np.array(list2)
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print("Numpy array dot product time:", end-start)


Python list dot product time: 0.2238004207611084
Numpy array dot product time: 0.001890420913696289


In [10]:
#4. Matrix Multiplication
import numpy as np
import time

size_mat = 1000

# Python lists
mat1 = [[i for i in range(size_mat)] for j in range(size_mat)]
mat2 = [[i for i in range(size_mat)] for j in range(size_mat)]
start = time.time()
res_list = [[sum(mat1[i][k]*mat2[k][j] for k in range(size_mat)) for j in range(size_mat)] for i in range(size_mat)]
end = time.time()
print("Python list matrix multiplication time:", end-start)

# Numpy arrays
mat_np1 = np.random.random((size_mat, size_mat))
mat_np2 = np.random.random((size_mat, size_mat))
start = time.time()
res_np = np.dot(mat_np1, mat_np2)
end = time.time()
print("Numpy array matrix multiplication time:", end-start)


Python list matrix multiplication time: 174.19352984428406
Numpy array matrix multiplication time: 0.06425619125366211
